sudo: required

services:
  - docker

install: true

script:
  - docker build -t helm-gke .

before_deploy:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  - docker tag helm-gke $CI_REGISTRY_USER/helm-gke:$TRAVIS_TAG
  - docker tag helm-gke $CI_REGISTRY_USER/helm-gke:latest

deploy:
  - provider: script
    script: docker push $CI_REGISTRY_USER/helm-gke:$TRAVIS_TAG && docker push $CI_REGISTRY_USER/helm-gke:latest
    on:
      tags: true
